vim.keymap.set("n", "<leader>pd", function()
	require("overlook.api").peek_definition()
end)
vim.keymap.set("n", "<leader>pc", function()
	require("overlook.api").close_all()
end)
vim.keymap.set("n", "<leader>pu", function()
	require("overlook.api").restore_poput()
end)
vim.keymap.set("n", "<leader>pv", function()
	require("overlook.api").open_in_vsplit()
end)
